name: cap3d_filter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.9
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - idna==3.7
      - joblib==1.4.0
      - nltk==3.8.1
      - numpy==1.26.4
      - pandas==2.2.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.4.16
      - requests==2.31.0
      - tqdm==4.66.2
      - tzdata==2024.1
      - urllib3==2.2.1
